wandb:
    entity: seonjong
    project: SORIE
    group: baseline
    experiment: layoutlm_large
    use_wandb: True # trainer에서 wandb를 사용할지 안할지
    online: True # 온라인으로 할지 오프라인으로 할지

save_dir : layoutlm_large
do_predict: True

data:
    path: data/
    dataset: Ssunbell/SORIE_baseline
    preprocess: BaselinePreprocess
    is_split_into_words: False
    add_image_data: True
    
model:
    model_name : microsoft/layoutlm-large-uncased
    model_class : BaselineModel
    trainer_class: BaselineTrainer
    metric_class : BaselineMetrics
    optimizer : AdamW

train:
    batch_size: 32
    test_batch_size: 32
    num_labels: 5
    max_epoch: 10
    dropout_rate : 0.1
    learning_rate: 1e-6
    num_workers: 4
    max_length : 30
    seed: 42
    gpus: 1