wandb:
    entity: seonjong
    project: SORIE
    group: baseline
    experiment: layoutlm
    use_wandb: True # trainer에서 wandb를 사용할지 안할지
    online: True # 온라인으로 할지 오프라인으로 할지

save_dir : layoutlm
do_predict: True

data:
    path: data/
    dataset: Ssunbell/SROIE_baseline
    preprocess: BaselinePreprocess
    is_split_into_words: False
    add_image_data: False
    
model:
    model_name : microsoft/layoutlm-base-uncased
    model_class : BaselineModel
    trainer_class: BaselineTrainer
    metric_class : BaselineMetrics
    optimizer : AdamW

train:
    batch_size: 128
    test_batch_size: 128
    num_labels: 5
    max_epoch: 2
    dropout_rate : 0.1
    learning_rate: 5e-5
    num_workers: 4
    max_length : 30
    seed: 42
    gpus: 1