wandb:
    entity: seonjong
    project: SORIE
    group: layoutlmv3
    experiment: layoutlmv3_large_sequence
    use_wandb: True # trainer에서 wandb를 사용할지 안할지
    online: True # 온라인으로 할지 오프라인으로 할지

save_dir : layoutlmv3_large_sequence
do_predict: True

data:
    path: data/
    dataset: Ssunbell/SROIE_layoutlmv2_sequence
    preprocess: LayoutLMv3Preprocess
    is_split_into_words: True
    add_image_data: True
    
model:
    model_name : microsoft/layoutlmv3-large
    model_class : LayoutLMv3Model
    trainer_class: BaselineTrainer
    metric_class : BaselineMetrics
    optimizer : AdamW

train:
    batch_size: 4
    test_batch_size: 4
    num_labels: 5
    max_epoch: 2
    dropout_rate : 0.1
    learning_rate: 5e-6
    num_workers: 4
    max_length : 512
    seed: 42
    gpus: 1