name: Build Test

on:
  pull_request:
    branches:
      - dev

jobs:
  Build:
    runs-on: macos-14

    steps:
      # 저장소의 코드를 체크아웃
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Check LFS files
        run: git lfs ls-files

      - name: ⚙️ Write xcconfig
        run: |
          echo "GPT_API_KEY = $GPT_API_KEY" >> $CONFIG_FILE_PATH
          echo "KAKAO_NATIVE_APP_KEY = $KAKAO_NATIVE_APP_KEY" >> $CONFIG_FILE_PATH
          echo "NOTIFICATION_KEY = $NOTIFICATION_KEY" >> $CONFIG_FILE_PATH
        env:
          GPT_API_KEY: ${{ secrets.GPT_API_KEY }}
          KAKAO_NATIVE_APP_KEY: ${{ secrets.KAKAO_NATIVE_APP_KEY }}
          NOTIFICATION_KEY: ${{ secrets.NOTIFICATION_KEY }}
          CONFIG_FILE_PATH: ${{ 'GimiFeedback/GimiFeedback/App/Config.xcconfig' }}

      - name: Decrypt GoogleService-Info.plist
        run: |
          echo "::add-mask::${GOOGLE_SERVICE_INFO_PWD}"
          gpg -d -o $DECRYPTED_GOOGLESERVICE_FILE_PATH \
            --pinentry-mode=loopback \
            --passphrase "$GOOGLE_SERVICE_INFO_PWD" \
            .github/secrets/GoogleService-Info.plist.gpg
        env:
          GOOGLE_SERVICE_INFO_PWD: ${{ secrets.GOOGLE_SERVICE_INFO_PWD }}
          DECRYPTED_GOOGLESERVICE_FILE_PATH: ${{ 'GimiFeedback/GimiFeedback/App/GoogleService-Info.plist' }}

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Print Xcode & CLT
        run: |
          xcodebuild -version
          xcode-select -p

      - name: List simulators
        run: xcrun simctl list devices available

      - name: 🛠 Start xcode build 
        run: |
          xcodebuild \
            -project GimiFeedback/GimiFeedback.xcodeproj \
            -scheme GimiFeedback \
            -sdk iphoneos \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
            -skipPackagePluginValidation \
            clean build